### ISSUE TITLE
Battery measurement not working

### ISSUE THREAD

**Issue by dig301** [4pplet/BLE-Test#3]
Is the battery measurement working by default?
I am a noob regarding zmk and by default my laptop (running Ubuntu 22.04)  does not show the battery level of the keyboard.

Can anyone help me? Thanks in advance

**Comment by 4pplet** [comment]
Hey! Sorry for the late response

Battery measurement should work and be enabled by default. There's some more info on it here: https://zmk.dev/docs/features/battery

My suggestion would be to try and flash the latest ZMK on it and/or ask in the ZMK discord if there's some known issue with ZMK and Ubuntu regarding reporting battery level.

Unfortunately, I'm not using Ubuntu, so I can't say how it should be displayed/reported in OS.
