### ISSUE TITLE
Very high battery drain?

### ISSUE THREAD

**Issue by pseudobacon** [4pplet/BLE-Test#4]
I built my own cyber60 mxhs version and have firmware compiled from July 23 2023 and seem to be having very high battery drain. I am using a 1460mah battery which I have used in a similar keyboard with a nRF52810 chip - [GT-BLE60](https://github.com/genokolar/Lotkb_Keyboard_PCB) and the keyboard will only last maybe 2-3 days maximum. On my other bluetooth keyboard I am able to get months of battery life. 

I'm looking to see if there is a way to diagnose this drain either in software or hardware?

**Comment by 4pplet** [comment]
I would suspect a short somewhere, since the battery drain is very high. Are all functions working?

**Comment by pseudobacon** [comment]
As far as I'm aware, all functions are working. The battery charges and discharges of course, all the keys are working on the keyboard. I've remapped a couple of keys from the default layout as well, including swapping the rotary encoder volume up and down behaviour back to what it was and that seems fine. I have it paired with two different devices, and swapping them is also fine too.

**Comment by 4pplet** [comment]
It's really hard for me to tell. I'd still suggest looking for shorts. Also make sure the transistor that shuts of underglow when not active works for example.

**Comment by pseudobacon** [comment]
Hmm well the undergrow toggle is working, all LEDs turn on and off as expected. I'll see if I can get my hands on a thermal camera
