### ISSUE TITLE
Case compatibility list?

### ISSUE THREAD

**Issue by cfergeau** [4pplet/BLE-Test#5]
A list of compatible cases similar to https://docs.google.com/spreadsheets/u/2/d/13Lbbcl5IB17AtRAp6NcSjG65x_7uYAqBwbp5UiGhyJw/htmlview# would be useful to have.
I've seen mentions of the tofu60, the bakeneko, the frog mini, and maybe the unikorn, I don't know if there are others where the PCB is known to fit (or not to fit :)

**Comment by 4pplet** [comment]
Thanks for suggesting this! 

I have started on a compatibility list. If anyone have more input re. usage of cases, please make a PR and add info or drop me a email/PM.

https://github.com/4pplet/cyber60/blob/master/COMPAT.md
